version: '3.6'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    ports:
      - "8123:8123"
    volumes:
      - ./data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime
    depends_on:
      - mqtt
    privileged: true
    restart: always
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mqtt:/mosquitto
    restart: always
  zigbee:
    image: koenkk/zigbee2mqtt
    depends_on:
      - mqtt
    volumes:
      - ./data/zigbee:/app/data
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    restart: always
